# PROVIDED – production profile (Docker Day 10)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartbudget}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sb_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sb_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.h2.console.enabled=false
spring.sql.init.mode=never
